export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_HOSPITALS = 'FETCH_HOSPITALS'
export const FETCH_HOSPITAL_NEEDS = 'FETCH_HOSPITAL_NEEDS'
